In [2]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_parquet("D:/AHU/rdm-wach-ai/data/raw/e0101.parquet")
df.head()

,time,result,table,controller,site,digital_input_1_and_2,power_factor_avg,power_factor_l1,power_factor_l2,power_factor_l3,...,power_l2,power_l3,power_total,energy_export,energy_import,reactive_power_l1,reactive_power_l2,reactive_power_l3,reactive_power_total,ahu_id
0,2025-10-30 08:15:00+00:00,NaN,5.228070,NaN,NaN,0.0,0.777500,0.747500,0.757500,0.827500,...,0.979637,0.985205,2.841448,399.9,5229.175000,0.792034,0.853977,0.678053,2.322438,e0101
1,2025-10-30 08:30:00+00:00,NaN,5.000000,NaN,NaN,0.0,0.776667,0.746667,0.756667,0.820000,...,0.982117,0.984874,2.850560,399.9,5230.200000,0.785323,0.849094,0.673866,2.317460,e0101
2,2025-10-30 08:45:00+00:00,NaN,5.333333,NaN,NaN,0.0,0.776667,0.746667,0.756667,0.826667,...,0.990519,0.993406,2.877733,399.9,5230.866667,0.796678,0.859312,0.682276,2.339780,e0101
3,2025-10-30 09:00:00+00:00,NaN,5.380952,NaN,NaN,0.0,0.766667,0.740000,0.736667,0.826667,...,0.907651,0.995470,2.798767,399.9,5231.533333,0.807439,0.838336,0.690075,2.333897,e0101
4,2025-10-30 09:15:00+00:00,NaN,5.769231,NaN,NaN,0.0,0.760000,0.740000,0.730000,0.820000,...,0.896568,0.990869,2.779920,399.9,5232.300000,0.806080,0.839858,0.692691,2.345990,e0101

In [12]:
len(df)

10047

In [16]:
df.columns

Index(['time', 'result', 'table', 'controller', 'site',
       'digital_input_1_and_2', 'power_factor_avg', 'power_factor_l1',
       'power_factor_l2', 'power_factor_l3', 'units', 'current_l1_thd',
       'current_l3_thd', 'current_unbalance', 'volts_l1_thd', 'volts_l2_thd',
       'volts_l3_thd', 'volts_unbalance', 'current_avg', 'current_l1',
       'current_l2', 'current_l3', 'freq', 'volts_l1_l2', 'volts_l1_n',
       'volts_l2_l3', 'volts_l2_n', 'volts_l3_l1', 'volts_l3_n',
       'volts_l_l_avg', 'volts_l_n_avg', 'apparent_power_demand',
       'apparent_power_l1', 'apparent_power_l2', 'apparent_power_l3',
       'apparent_power_total', 'apparent_energy', 'reactive_power_demand',
       'reactive_energy_export', 'reactive_energy_import', 'max_power_demand',
       'power_demand', 'power_l1', 'power_l2', 'power_l3', 'power_total',
       'energy_export', 'energy_import', 'reactive_power_l1',
       'reactive_power_l2', 'reactive_power_l3', 'reactive_power_total',
       'ahu_id'],
      dtype='object')

In [20]:
#to see the merged data 
df = pd.read_parquet("D:/AHU/rdm-wach-ai/data/merged/ahu_all.parquet")
df.tail(60)

,time,result,table,controller,site,digital_input_1_and_2,power_factor_avg,power_factor_l1,power_factor_l2,power_factor_l3,...,power_l2,power_l3,power_total,energy_export,energy_import,reactive_power_l1,reactive_power_l2,reactive_power_l3,reactive_power_total,ahu_id
30081,2026-02-11 09:00:00+00:00,NaN,5.153846,NaN,NaN,0.0,0.800000,0.800000,0.800000,0.810000,...,2.014300,2.017020,6.589430,391.1,30397.900000,1.921400,1.508530,1.485060,4.919690,e0103
30082,2026-02-11 09:15:00+00:00,NaN,5.615385,NaN,NaN,0.0,0.800000,0.800000,0.800000,0.800000,...,1.979570,1.980020,6.480750,391.1,30398.600000,1.904000,1.493530,1.472190,4.882690,e0103
30083,2026-02-11 09:30:00+00:00,NaN,5.292683,NaN,NaN,0.0,0.806667,0.800000,0.800000,0.806667,...,2.009397,2.011447,6.568383,391.1,30399.133333,1.908713,1.497783,1.476137,4.889970,e0103
30084,2026-02-11 09:45:00+00:00,NaN,5.512195,NaN,NaN,0.0,0.810000,0.803333,0.800000,0.810000,...,2.028430,2.028040,6.625340,391.1,30399.600000,1.908760,1.499590,1.475173,4.885830,e0103
30085,2026-02-11 10:00:00+00:00,NaN,5.421053,NaN,NaN,0.0,0.810000,0.806667,0.803333,0.810000,...,2.031917,2.026467,6.640143,391.1,30400.233333,1.898920,1.494870,1.464903,4.856453,e0103
30086,2026-02-11 10:15:00+00:00,NaN,5.205128,NaN,NaN,0.0,0.810000,0.800000,0.810000,0.810000,...,2.022410,2.019800,6.617190,391.1,30400.700000,1.888480,1.486710,1.456110,4.828820,e0103
30087,2026-02-11 10:30:00+00:00,NaN,5.302326,NaN,NaN,0.0,0.800000,0.800000,0.800000,0.800000,...,1.995640,1.995660,6.547540,391.1,30401.700000,1.914930,1.508010,1.480990,4.897150,e0103
30088,2026-02-11 10:45:00+00:00,NaN,5.404762,NaN,NaN,0.0,0.810000,0.810000,0.810000,0.810000,...,2.036770,2.039640,6.676080,391.1,30402.400000,1.919480,1.506030,1.483230,4.907190,e0103
30089,2026-02-11 11:00:00+00:00,NaN,4.785714,NaN,NaN,0.0,0.803333,0.803333,0.803333,0.803333,...,2.049610,2.048380,6.720527,391.1,30402.866667,1.961260,1.542523,1.516363,5.019497,e0103
30090,2026-02-11 11:15:00+00:00,NaN,5.368421,NaN,NaN,0.0,0.800000,0.800000,0.800000,0.800000,...,2.059457,2.058053,6.743913,391.1,30403.700000,1.988825,1.567730,1.539042,5.096380,e0103
30091,2026-02-11 11:30:00+00:00,NaN,5.390244,NaN,NaN,0.0,0.800000,0.800000,0.800000,0.800000,...,2.053860,2.050030,6.708370,391.1,30404.600000,1.981770,1.564310,1.533210,5.080560,e0103
30092,2026-02-11 11:45:00+00:00,NaN,5.434783,NaN,NaN,0.0,0.800000,0.800000,0.800000,0.800000,...,2.041190,2.041300,6.664120,391.1,30405.300000,1.981180,1.563950,1.534240,5.088370,e0103
30093,2026-02-11 12:00:00+00:00,NaN,5.372093,NaN,NaN,0.0,0.800000,0.800000,0.790000,0.800000,...,2.035620,2.033850,6.680390,391.1,30406.000000,1.981060,1.565600,1.536290,5.082490,e0103
30094,2026-02-11 12:15:00+00:00,NaN,5.595238,NaN,NaN,0.0,0.800000,0.793333,0.796667,0.800000,...,2.043847,2.042543,6.686790,391.1,30406.533333,1.992293,1.574993,1.545110,5.115023,e0103
30095,2026-02-11 12:30:00+00:00,NaN,5.205128,NaN,NaN,0.0,0.796667,0.790000,0.796667,0.800000,...,2.043543,2.042353,6.674173,391.1,30407.100000,2.000513,1.580180,1.551183,5.132483,e0103
30096,2026-02-11 12:45:00+00:00,NaN,5.536585,NaN,NaN,0.0,0.790000,0.786667,0.790000,0.796667,...,2.026310,2.026477,6.628373,391.1,30407.966667,2.001983,1.578463,1.549740,5.123847,e0103
30097,2026-02-11 13:00:00+00:00,NaN,5.190476,NaN,NaN,0.0,0.793333,0.786667,0.790000,0.793333,...,2.018863,2.020090,6.625653,391.1,30408.733333,1.992673,1.571627,1.538677,5.098720,e0103
30098,2026-02-11 13:15:00+00:00,NaN,5.465116,NaN,NaN,0.0,0.800000,0.800000,0.790000,0.800000,...,2.037570,2.034530,6.676880,391.1,30409.200000,1.989000,1.568740,1.535630,5.092560,e0103
30099,2026-02-11 13:30:00+00:00,NaN,5.069767,NaN,NaN,0.0,0.790000,0.800000,0.790000,0.800000,...,2.041190,2.040730,6.668150,391.1,30409.900000,1.993220,1.571580,1.544630,5.118570,e0103
30100,2026-02-11 13:45:00+00:00,NaN,5.454545,NaN,NaN,0.0,0.790000,0.790000,0.790000,0.790000,...,2.016880,2.016470,6.620290,391.1,30410.500000,1.989540,1.568540,1.535200,5.095140,e0103
30101,2026-02-11 14:00:00+00:00,NaN,5.290909,NaN,NaN,0.0,0.790000,0.790000,0.790000,0.800000,...,2.019635,2.026323,6.628970,391.1,30411.300000,1.998940,1.573610,1.548550,5.122050,e0103
30102,2026-02-11 14:15:00+00:00,NaN,5.142857,NaN,NaN,0.0,0.790000,0.790000,0.790000,0.800000,...,2.044820,2.043250,6.699030,391.1,30412.100000,1.998800,1.573110,1.547160,5.119110,e0103
30103,2026-02-11 14:30:00+00:00,NaN,5.619048,NaN,NaN,0.0,0.790000,0.800000,0.790000,0.800000,...,2.031470,2.032420,6.654860,391.1,30412.800000,1.996810,1.577120,1.542850,5.122630,e0103
30104,2026-02-11 14:45:00+00:00,NaN,5.073171,NaN,NaN,0.0,0.790000,0.790000,0.790000,0.800000,...,2.015710,2.012750,6.600750,391.1,30413.500000,1.989260,1.568100,1.540480,5.097690,e0103
30105,2026-02-11 15:00:00+00:00,NaN,5.133333,NaN,NaN,0.0,0.790000,0.790000,0.790000,0.790000,...,2.028070,2.032800,6.661820,391.1,30414.300000,2.012570,1.580640,1.552150,5.136510,e0103
30106,2026-02-11 15:15:00+00:00,NaN,5.634146,NaN,NaN,0.0,0.790000,0.796667,0.790000,0.796667,...,2.040683,2.039000,6.690627,391.1,30414.700000,2.005057,1.577447,1.549283,5.128237,e0103
30107,2026-02-11 15:30:00+00:00,NaN,5.292683,NaN,NaN,0.0,0.790000,0.793333,0.790000,0.800000,...,2.041530,2.034747,6.683003,391.1,30415.433333,2.004033,1.580883,1.549617,5.133807,e0103
30108,2026-02-11 15:45:00+00:00,NaN,5.386364,NaN,NaN,0.0,0.790000,0.790000,0.790000,0.796667,...,2.037713,2.034243,6.673837,391.1,30416.000000,2.014693,1.588460,1.557837,5.159670,e0103
30109,2026-02-11 16:00:00+00:00,NaN,5.250000,NaN,NaN,0.0,0.790000,0.790000,0.790000,0.790000,...,2.044727,2.051087,6.705073,391.1,30416.866667,2.038320,1.602317,1.576563,5.214367,e0103
30110,2026-02-11 16:15:00+00:00,NaN,5.622642,NaN,NaN,0.0,0.790000,0.790000,0.790000,0.790000,...,2.063160,2.071200,6.755635,391.1,30417.550000,2.041595,1.607435,1.582355,5.231900,e0103
30111,2026-02-11 16:30:00+00:00,NaN,5.317073,NaN,NaN,0.0,0.790000,0.786667,0.786667,0.790000,...,2.056503,2.059523,6.729367,391.1,30418.233333,2.041493,1.610460,1.584600,5.241580,e0103
30112,2026-02-11 16:45:00+00:00,NaN,4.767442,NaN,NaN,0.0,0.790000,0.780000,0.780000,0.790000,...,2.044940,2.039577,6.686633,391.1,30418.966667,2.056423,1.624863,1.595083,5.277077,e0103
30113,2026-02-11 17:00:00+00:00,NaN,5.292683,NaN,NaN,0.0,0.790000,0.780000,0.780000,0.790000,...,2.055970,2.050887,6.712623,391.1,30419.733333,2.064953,1.635320,1.602877,5.293903,e0103
30114,2026-02-11 17:15:00+00:00,NaN,5.644068,NaN,NaN,0.0,0.785000,0.780000,0.780000,0.785000,...,2.064325,2.060985,6.750830,391.1,30420.600000,2.082875,1.646810,1.618555,5.346015,e0103
30115,2026-02-11 17:30:00+00:00,NaN,5.340000,NaN,NaN,0.0,0.783333,0.786667,0.783333,0.786667,...,2.052607,2.048847,6.714680,391.1,30421.233333,2.059380,1.627777,1.598147,5.285253,e0103
30116,2026-02-11 17:45:00+00:00,NaN,5.166667,NaN,NaN,0.0,0.790000,0.800000,0.790000,0.800000,...,2.041687,2.035957,6.664993,391.1,30421.900000,1.999680,1.580947,1.548143,5.130127,e0103
30117,2026-02-11 18:00:00+00:00,NaN,5.568966,NaN,NaN,0.0,0.790000,0.795000,0.790000,0.795000,...,2.046610,2.043590,6.691600,391.1,30422.700000,2.014985,1.591610,1.561895,5.167690,e0103
30118,2026-02-11 18:15:00+00:00,NaN,5.181818,NaN,NaN,0.0,0.790000,0.790000,0.790000,0.790000,...,2.050500,2.050647,6.715227,391.1,30423.400000,2.018723,1.591820,1.565097,5.169610,e0103
30119,2026-02-11 18:30:00+00:00,NaN,5.571429,NaN,NaN,0.0,0.790000,0.790000,0.790000,0.793333,...,2.047527,2.048103,6.717377,391.1,30424.200000,2.003477,1.578260,1.553947,5.134507,e0103
30120,2026-02-11 18:45:00+00:00,NaN,5.500000,NaN,NaN,0.0,0.790000,0.790000,0.790000,0.800000,...,2.043390,2.043915,6.699610,391.1,30425.000000,2.003490,1.577985,1.556000,5.142635,e0103
30121,2026-02-11 19:00:00+00:00,NaN,5.441860,NaN,NaN,0.0,0.790000,0.790000,0.790000,0.800000,...,2.038813,2.037547,6.671417,391.1,30425.633333,1.999170,1.576690,1.554367,5.135147,e0103
30122,2026-02-11 19:15:00+00:00,NaN,5.396226,NaN,NaN,0.0,0.790000,0.790000,0.795000,0.800000,...,2.062160,2.051615,6.707785,391.1,30426.450000,2.005890,1.585170,1.557710,5.145535,e0103
30123,2026-02-11 19:30:00+00:00,NaN,5.538462,NaN,NaN,0.0,0.796667,0.790000,0.800000,0.800000,...,2.080260,2.056383,6.748127,391.1,30427.266667,2.012337,1.590523,1.558653,5.158057,e0103
30124,2026-02-11 19:45:00+00:00,NaN,5.203704,NaN,NaN,0.0,0.792500,0.790000,0.792500,0.792500,...,2.079500,2.051645,6.753077,391.1,30428.025000,2.004328,1.585555,1.556220,5.144448,e0103
30125,2026-02-11 20:00:00+00:00,NaN,5.552632,NaN,NaN,0.0,0.790000,0.790000,0.790000,0.790000,...,2.082957,2.046507,6.728130,391.1,30428.866667,2.000863,1.587153,1.559220,5.145743,e0103
30126,2026-02-11 20:15:00+00:00,NaN,5.519231,NaN,NaN,0.0,0.790000,0.790000,0.790000,0.790000,...,2.086768,2.052905,6.725995,391.1,30429.500000,2.016890,1.593655,1.571448,5.182570,e0103
30127,2026-02-11 20:30:00+00:00,NaN,5.320755,NaN,NaN,0.0,0.790000,0.790000,0.790000,0.790000,...,2.083130,2.059378,6.740457,391.1,30430.400000,2.025472,1.592350,1.576925,5.196195,e0103
30128,2026-02-11 20:45:00+00:00,NaN,5.500000,NaN,NaN,0.0,0.790000,0.797500,0.792500,0.792500,...,2.083182,2.055922,6.722843,391.1,30431.500000,2.016342,1.590625,1.570772,5.176423,e0103
30129,2026-02-11 21:00:00+00:00,NaN,5.333333,NaN,NaN,0.0,0.790000,0.790000,0.800000,0.795000,...,2.076785,2.057625,6.722620,391.1,30432.450000,2.006840,1.577610,1.564270,5.152550,e0103
30130,2026-02-11 21:15:00+00:00,NaN,5.585366,NaN,NaN,0.0,0.790000,0.790000,0.800000,0.790000,...,2.077583,2.050733,6.720957,391.1,30433.266667,2.012697,1.580897,1.566040,5.160033,e0103
30131,2026-02-11 21:30:00+00:00,NaN,5.672727,NaN,NaN,0.0,0.790000,0.790000,0.800000,0.795000,...,2.077150,2.051400,6.707510,391.1,30433.850000,2.013205,1.577740,1.567800,5.161035,e0103
30132,2026-02-11 21:45:00+00:00,NaN,5.461538,NaN,NaN,0.0,0.790000,0.790000,0.800000,0.800000,...,2.080307,2.061362,6.750243,391.1,30434.725000,2.013418,1.577503,1.567085,5.161423,e0103
30133,2026-02-11 22:00:00+00:00,NaN,5.425000,NaN,NaN,0.0,0.790000,0.790000,0.800000,0.800000,...,2.101210,2.077310,6.759780,391.1,30435.700000,2.022070,1.583200,1.572250,5.171470,e0103
30134,2026-02-11 22:15:00+00:00,NaN,5.400000,NaN,NaN,0.0,0.790000,0.790000,0.800000,0.800000,...,2.087545,2.068355,6.747930,391.1,30436.300000,2.015470,1.578288,1.568770,5.160588,e0103
30135,2026-02-11 22:30:00+00:00,NaN,5.448276,NaN,NaN,0.0,0.800000,0.790000,0.800000,0.797500,...,2.087398,2.060000,6.739868,391.1,30437.375000,2.004863,1.572232,1.565338,5.145312,e0103
30136,2026-02-11 22:45:00+00:00,NaN,5.490196,NaN,NaN,0.0,0.800000,0.790000,0.800000,0.795000,...,2.092345,2.065495,6.771310,391.1,30438.300000,2.010690,1.573450,1.565200,5.147155,e0103
30137,2026-02-11 23:00:00+00:00,NaN,5.444444,NaN,NaN,0.0,0.795000,0.790000,0.800000,0.800000,...,2.080055,2.058490,6.735950,391.1,30439.050000,2.009580,1.570885,1.563465,5.141445,e0103
30138,2026-02-11 23:15:00+00:00,NaN,5.519231,NaN,NaN,0.0,0.790000,0.790000,0.800000,0.792500,...,2.078365,2.060307,6.735642,391.1,30439.925000,2.018970,1.581113,1.573335,5.169607,e0103
30139,2026-02-11 23:30:00+00:00,NaN,5.560000,NaN,NaN,0.0,0.800000,0.800000,0.792500,0.800000,...,2.026530,2.025533,6.654037,391.1,30513.950000,1.963753,1.553350,1.518750,5.043652,e0103
30140,2026-02-11 23:45:00+00:00,NaN,5.384615,NaN,NaN,0.0,0.800000,0.800000,0.800000,0.800000,...,2.033765,2.039385,6.682995,391.1,30514.750000,1.957700,1.544475,1.512355,5.018890,e0103